version: "3.9"

services:
  web:
  # nombre de la aplicacion
    container_name: nodeBase
    restart: no #always
    build: .
    ports:
      - "777:3000"
    volumes:
      - .:/usr/src/app
 
      #comando para correr 
      #docker-compose build
      #docker-compose up
      #docker ps